version: '3.1'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
    volumes:
      - db-data:/var/lib/mysql

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - default
    ports:
    - "8080:8080"

volumes:
  db-data:
    driver: local
