CREATE TABLE IF NOT EXISTS day (
    id VARBINARY(36) NOT NULL PRIMARY KEY,
    dayDate DATETIME NOT NULL,
    exerciseId VARBINARY(36) NOT NULL,
    FOREIGN KEY (exerciseId) REFERENCES exercise(id)
) ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4;
