CREATE TABLE IF NOT EXISTS exerciseset (
    id VARBINARY(36) NOT NULL PRIMARY KEY,
    dayId VARBINARY(36) NOT NULL,
    setNo INT NOT NULL,
    rep INT NOT NULL,
    weight FLOAT NOT NULL,
    FOREIGN KEY (dayId) REFERENCES day(id)
) ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4;
